extend: base.yaml
node_id: learner_6
role: learner
listen:
  host: localhost
  port: 50058
connect_to:
- trainer@localhost:50051
learner:
  type: default
  args:
    batch_size: 64
    lr: 0.01
    device: cuda
datasets:
- type: emnist
  split: train
  args:
    data_dir: ./data
    download: true
  partition:
    strategy: dirichlet
    num_partitions: 10
    config:
      alpha: 0.5
      seed: 42
    partition_id: 6
model:
  type: simple_cnn
  args:
    num_classes: 62
